#!/usr/bin/env python
import subprocess
import re
import socket

try:
    result = subprocess.run(
        ["brightnessctl"], capture_output=True, text=True, check=True
    )
    text = result.stdout.strip()
    last_line = text.split("\n")[-1]
    brightness_percent = re.search(r"\((\d+%)", text).group(1)
    brightness = f"🌞 {brightness_percent}"

    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    abstract_socket_name = "status_socket"
    sock.connect("\0" + abstract_socket_name)

    message = f"brightness\n{brightness}"
    sock.sendall(message.encode("utf-8"))
    sock.close()
except subprocess.CalledProcessError as e:
    # Handle errors in the command execution
    print("An error occurred while trying to execute the command:")
    print(e.stderr)
