#!/usr/bin/env python
import subprocess
import re
import socket

try:
    result = subprocess.run(
        ["amixer", "get", "Master"], capture_output=True, text=True, check=True
    )
    text = result.stdout.strip()
    last_line = text.split("\n")[-1]
    muted = "🔇" if "[off]" in last_line else "🔊"
    volume = re.search(r"\[(\d+%)", text).group(1)

    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    abstract_socket_name = "status_socket"
    sock.connect("\0" + abstract_socket_name)

    message = f"volume\n{muted} {volume}"
    sock.sendall(message.encode("utf-8"))
    sock.close()
except subprocess.CalledProcessError as e:
    # Handle errors in the command execution
    print("An error occurred while trying to execute the command:")
    print(e.stderr)
